services:
  baseDatos:
    image: postgres:16
    container_name: baseDatos
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  django:
    build:
      context: .
      dockerfile: config/django-img/dockerfile
    image: fei2026tp:0.1
    container_name: django
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    restart: always
    depends_on:
      - baseDatos
