# Generated by Django 6.0.5 on 2026-06-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('observacion', models.CharField(max_length=256)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.materia')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.reserva_aula')),
            ],
        ),
    ]
