FROM python:3.12.2-bookworm

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install -r requirements.txt

COPY config/django-img/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
